### ISSUE TITLE
缺少东西啊

### ISSUE THREAD

**Issue by shichunlei** [kymjs/Contacts#1]
缺少东西啊

**Comment by kymjs** [comment]
没有发现缺什么

**Comment by shichunlei** [comment]
我没找到这几个文件

import org.kymjs.kjframe.KJBitmap;
import org.kymjs.kjframe.widget.AdapterHolder;
import org.kymjs.kjframe.widget.KJAdapter;
import org.kymjs.kjframe.KJActivity;
import org.kymjs.kjframe.KJHttp;
import org.kymjs.kjframe.http.HttpCallBack;
import org.kymjs.kjframe.http.HttpConfig;
import org.kymjs.kjframe.ui.BindView;
import org.kymjs.kjframe.utils.KJLoger;

我使用的eclipse
